### PR TITLE
add support for kibana6

### PR DESCRIPTION
**Pull request by iksaif**

### CODE REVIEW

**Comment by iksaif** [comment]
@InformatiQ / @Thib17 can you take over this PR ?

**Comment by florian-asche** [comment]
I tested this PR. Works good. Found some other problems. I send a PR after this PR is done to prevent conflicts.

**Comment by iksaif** [comment]
@florian-asche feel free to include my patch in your PR because I'm switching jobs and will probably not work on chef-kibana anymore :).

**Comment by erebe** [comment]
@florian-asche what problems have you found ?
I am going to take over the PR in order to support kibana 6 at Criteo. So I may fix things in this one as well.

@mburns 
What are you thoughts on this PR ? Do you want this PR https://github.com/realityforge/chef-kibana/pull/116 to be merged first before considering this one ? What would you like to see in it in order to merge it ?

**Pull request closed without merging**
