### PR TITLE
config: unify kibana3 and kibana4 url

### PR DESCRIPTION
**Pull request by wdauchy**
use the same system to templatise the ES url for both kibana3 and
kibana4

### CODE REVIEW

**Comment by wdauchy** [comment]
seems like tests are failing because of nginx; I don't think it is related to my changes

**Comment by wdauchy** [comment]
@realityforge or @cyberflow - any chance to review this?

**Comment by realityforge** [comment]
Unfortunately atm I am on a deathmarch and then off to holiday so wont be able to take a look :(

**Comment by cyberflow** [comment]
@wdauchy I'm not sure, but what happened if es_host will be 0.0.0.0? Because for kibana 3 it's configure nginx/apache and if i understand correctly config.js in kibana3 configuring browser part. It's working for you?

**Comment by wdauchy** [comment]
@cyberflow good point. I was just expecting node['kibana']['elasticsearch']['hosts'] would be set to correct values but indeed the default is 127.0.0.1 which makes it non working as well as 0.0.0.0.

What do you think if I test node['kibana']['elasticsearch']['hosts'].first value?

e.g
```
if ['127.0.0.1', '0.0.0.0'].include? node['kibana']['elasticsearch']['hosts'].first
  elasticsearch: "http://" + window.location.hostname + ":<%= @es_port %>",
else
  elasticsearch: "http://<%= @es_host %>:<%= @es_port %>",
end
```

**Comment by cyberflow** [comment]
@wdauchy I think that it's not make sense do it with only '.first' element of array. If you want to do this will be better make config with all addresses of elasticsearch cluster. Also i prefer to do special attribute for `windows.location.hostname` option in kibana 3 config. I think it's will be more flexible.

**Comment by wdauchy** [comment]
@cyberflow I also agree .first is not ideal but that's precisely what is used in kibana4.rb:
`./recipes/kibana4.rb:    es_host:    node['kibana']['elasticsearch']['hosts'].first,`

**Comment by realityforge** [comment]
Closing due to lack of activity and out of date

**Pull request closed without merging**
