### PR TITLE
Add multi-platform coverage to our unit tests(cyberflow)

### PR DESCRIPTION
**Pull request by mburns**
Refactor/cherry-pick logic from #101 with respect to unit tests (and basic tooling/chef12 compatibility).

Currently, the majority of our unit tests only run against Ubuntu. We should run all tests against the platforms we claim to support (ubuntu 14/16, centos 6/7).

# TODO
- [x] fix Travis
- [x] unit tests pass
- [ ] all tests pass

### CODE REVIEW

**Comment by drenalin23** [comment]
lgtm

**Comment by mburns** [comment]
just need to coordinate with @realityforge to get Travis building PRs again.

**Comment by realityforge** [comment]
Okay - I think it has all been re-enabled. Kick me if you need me to do anything more.

**Comment by mburns** [comment]
Passes unit tests.

There are some issues with package installs on some of the integration tests. Will need to address those before cutting a new release.

**Pull request merged**
